# Generated by Django 4.2.7 on 2026-02-16 20:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(help_text='Name of the store/merchant', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField(help_text='Date when the purchase was made')),
                ('image_url', models.URLField(help_text='URL to bill image in Firebase Storage', max_length=500)),
                ('image_hash', models.CharField(db_index=True, help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('ocr_text', models.TextField(blank=True, help_text='Full text extracted from OCR')),
                ('has_warranty_items', models.BooleanField(default=False, help_text='Does this bill have any items with warranty?')),
                ('warranty_items_count', models.IntegerField(default=0, help_text='Number of items with warranty', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product/item name', max_length=255)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('appliances', 'Appliances'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('groceries', 'Groceries'), ('health', 'Health & Beauty'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('books', 'Books & Media'), ('automotive', 'Automotive'), ('home', 'Home & Garden'), ('other', 'Other')], default='other', help_text='Item category', max_length=50)),
                ('ml_predicted_category', models.CharField(blank=True, help_text='Category predicted by ML model', max_length=50)),
                ('ml_category_confidence', models.FloatField(blank=True, help_text='ML confidence score for category (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('category_corrected_by_user', models.BooleanField(default=False, help_text='Did user manually change the category?')),
                ('ml_predicted_warranty', models.BooleanField(default=False, help_text='Does ML predict this item has warranty?')),
                ('ml_warranty_confidence', models.FloatField(blank=True, help_text='ML confidence score for warranty prediction (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('warranty_corrected_by_user', models.BooleanField(default=False, help_text='Did user manually change warranty status?')),
                ('has_warranty', models.BooleanField(default=False, help_text='Does this item have a warranty?')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill')),
            ],
            options={
                'ordering': ['bill', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.IntegerField(help_text='Warranty duration number', validators=[django.core.validators.MinValueValidator(1)])),
                ('period_unit', models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='months', help_text='Unit of warranty period', max_length=10)),
                ('start_date', models.DateField(help_text='Warranty start date')),
                ('expiry_date', models.DateField(help_text='Warranty expiration date')),
                ('source', models.CharField(choices=[('auto_detected', 'Auto-detected from OCR'), ('user_manual', 'User Manual Entry'), ('verbal', 'Verbal/Store Policy')], default='user_manual', help_text='How was this warranty information obtained?', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional warranty notes')),
                ('warranty_card_url', models.URLField(blank=True, help_text='URL to warranty card image in Firebase', max_length=500)),
                ('warranty_card_path', models.CharField(blank=True, help_text='Firebase storage path for warranty card', max_length=500)),
                ('has_warranty_card', models.BooleanField(default=False, help_text='Is there a warranty card uploaded?')),
                ('reminder_sent_30_days', models.BooleanField(default=False, help_text='30-day reminder sent?')),
                ('reminder_sent_7_days', models.BooleanField(default=False, help_text='7-day reminder sent?')),
                ('reminder_sent_1_day', models.BooleanField(default=False, help_text='1-day reminder sent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='bills.billitem')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='bills_warra_expiry__8e4f42_idx'), models.Index(fields=['start_date'], name='bills_warra_start_d_d0ffb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill', 'has_warranty'], name='bills_billi_bill_id_90c040_idx'),
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['category'], name='bills_billi_categor_2702f9_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['-purchase_date'], name='bills_bill_purchas_db2ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', '-purchase_date'], name='bills_bill_user_id_60c5e7_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['image_hash'], name='bills_bill_image_h_c2fbd7_idx'),
        ),
    ]
