# Generated by Django 4.2.7 on 2026-03-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('receipt', 'Receipt'), ('warranty', 'Warranty')], max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('sinhala', 'Sinhala'), ('tamil', 'Tamil')], max_length=20)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('firebase_image_url', models.URLField(blank=True)),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(default='Others', max_length=100)),
                ('category_confidence', models.FloatField(default=0.0)),
                ('warranty_detected', models.BooleanField(default=False)),
                ('warranty_confidence', models.FloatField(default=0.0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bills.bill')),
            ],
            options={
                'ordering': ['bill', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_period_months', models.IntegerField(default=12)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notify_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('warranty_card_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='bills.bill')),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='bills.billitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bill'], name='bills_warra_bill_id_41e016_idx'), models.Index(fields=['expiry_date'], name='bills_warra_expiry__8e4f42_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='billitem',
            index=models.Index(fields=['bill'], name='bills_billi_bill_id_29decf_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['-created_at'], name='bills_bill_created_51b69d_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', '-created_at'], name='bills_bill_user_id_e0fe0c_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['image_hash'], name='bills_bill_image_h_c2fbd7_idx'),
        ),
    ]
