// types/warranty.types.ts

/**
 * ============================================================================
 * WARRANTY TYPE DEFINITIONS
 * ============================================================================
 * 
 * TypeScript interfaces for warranty data structure.
 * Ensures type safety across the entire warranty tracker feature.
 */

/**
 * Main Warranty Interface
 * 
 * Represents a complete warranty record stored in Firestore.
 * All warranty operations use this structure.
 * 
 * @interface Warranty
 */
export interface Warranty {
  // ========== IDENTIFICATION ==========
  
  /** Unique warranty ID (auto-generated by Firestore) */
  id: string;
  
  /** User who owns this warranty (from Firebase Auth) */
  userId: string;
  
  /** Optional: Link to the bill document this warranty came from */
  billId?: string;
  
  // ========== PRODUCT INFORMATION ==========
  
  /** Product name (e.g., "iPhone 17 Pro", "Samsung TV") */
  productName: string;
  
  /** Optional: Product image URL from Firebase Storage */
  productImage?: string;
  
  /** Optional: Brand/Manufacturer (e.g., "Apple", "Samsung") */
  brand?: string;
  
  /** Optional: Serial number for warranty claims */
  serialNumber?: string;
  
  // ========== WARRANTY DETAILS ==========
  
  /** Date when the product was purchased */
  purchaseDate: Date;
  
  /** How long the warranty lasts (in months) */
  warrantyDuration: number;
  
  /** Calculated expiry date (purchaseDate + warrantyDuration) */
  expiryDate: Date;
  
  // ========== CALCULATED/DERIVED FIELDS ==========
  
  /** Days remaining until warranty expires (can be negative) */
  daysRemaining: number;
  
  /** Current warranty status based on daysRemaining */
  status: WarrantyStatus;
  
  // ========== METADATA ==========
  
  /** When this warranty was created in the app */
  createdAt: Date;
  
  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Warranty Status Type
 * 
 * Three possible states based on days remaining:
 * - 'active': More than 10 days remaining (safe)
 * - 'expiring_soon': 1-10 days remaining (warning)
 * - 'expired': 0 or negative days (critical)
 * 
 * @type WarrantyStatus
 */
export type WarrantyStatus = 'active' | 'expiring_soon' | 'expired';

/**
 * Warranty Form Data
 * 
 * Used when creating a new warranty from OCR scan or manual input.
 * Contains only the fields that users provide.
 * Other fields (id, status, etc.) are calculated automatically.
 * 
 * @interface WarrantyFormData
 */
export interface WarrantyFormData {
  /** Product name */
  productName: string;
  
  /** Optional: Product image URL */
  productImage?: string;
  
  /** Optional: Brand name */
  brand?: string;
  
  /** Optional: Serial number */
  serialNumber?: string;
  
  /** Purchase date */
  purchaseDate: Date;
  
  /** Warranty duration in months */
  warrantyDuration: number;
}

/**
 * Warranty Filter Type
 * 
 * Used for filtering warranties in the list view.
 * Allows users to see all warranties or filter by status.
 * 
 * @type WarrantyFilter
 */
export type WarrantyFilter = 'all' | 'active' | 'expiring_soon' | 'expired';